import type { AgentDefinition, DepartmentDefinition, DepartmentId } from "./types";

const departments: DepartmentDefinition[] = [
  {
    id: "research",
    name: "Research Department",
    mission: "Discover trends, folklore topics, competitor movements, and source material.",
    managerAgentId: "research-manager",
    channels: ["department-ops", "workflow-events", "memory-reflection"],
    escalationAgentId: "chief-creator-officer",
  },
  {
    id: "content",
    name: "Content Department",
    mission: "Transform approved research into scripts, hooks, thumbnails, captions, and packages.",
    managerAgentId: "content-manager",
    channels: ["department-ops", "workflow-events", "approval-gate"],
    escalationAgentId: "chief-creator-officer",
  },
  {
    id: "platform_operations",
    name: "Platform Operations",
    mission: "Prepare platform-ready posting packages and scheduling plans without public publishing.",
    managerAgentId: "platform-manager",
    channels: ["department-ops", "approval-gate", "incident-response"],
    escalationAgentId: "chief-creator-officer",
  },
  {
    id: "analytics",
    name: "Analytics Department",
    mission: "Read performance signals, explain movement, and generate optimization insights.",
    managerAgentId: "analytics-manager",
    channels: ["department-ops", "workflow-events", "memory-reflection"],
    escalationAgentId: "optimization-manager",
  },
  {
    id: "optimization",
    name: "Optimization Department",
    mission: "Improve strategies, prompts, workflows, and experiments through approval-gated proposals.",
    managerAgentId: "optimization-manager",
    channels: ["executive-briefing", "department-ops", "approval-gate"],
    escalationAgentId: "chief-creator-officer",
  },
  {
    id: "infrastructure",
    name: "Infrastructure Department",
    mission: "Monitor queues, workers, providers, configuration, and safe execution boundaries.",
    managerAgentId: "infrastructure-manager",
    channels: ["department-ops", "incident-response", "workflow-events"],
    escalationAgentId: "recovery-manager",
  },
  {
    id: "browser_operations",
    name: "Browser Operations Department",
    mission: "Plan governed Playwright sessions, validate web actions, audit screenshots, and keep browser automation dry-run until approved.",
    managerAgentId: "browser-ops-manager",
    channels: ["browser-ops", "workflow-events", "approval-gate", "incident-response"],
    escalationAgentId: "recovery-manager",
  },
  {
    id: "error_recovery",
    name: "Error Recovery Department",
    mission: "Triage incidents, retry safely, switch providers when allowed, and escalate risky failures.",
    managerAgentId: "recovery-manager",
    channels: ["incident-response", "approval-gate", "workflow-events"],
    escalationAgentId: "chief-creator-officer",
  },
  {
    id: "organizational_memory",
    name: "Organizational Memory Department",
    mission: "Capture workflow memories, reflections, reusable learnings, and future vector hooks.",
    managerAgentId: "memory-manager",
    channels: ["memory-reflection", "workflow-events", "executive-briefing"],
    escalationAgentId: "chief-creator-officer",
  },
];

const agents: AgentDefinition[] = [
  {
    id: "chief-creator-officer",
    name: "Chief Creator Officer",
    layer: "executive",
    role: "Executive commander for autonomous creator operations.",
    goals: ["Coordinate departments", "Approve high-risk strategy changes", "Protect brand and safety boundaries"],
    memorySummary: "Executive memory tracks brand direction, risk posture, approval patterns, and strategy shifts.",
    tools: ["workflow-planner", "approval-router", "executive-brief-generator"],
    permissions: ["research.read", "content.review", "analytics.read", "optimization.propose", "approval.request", "incident.report"],
    kpis: [
      { name: "Strategic alignment", value: 94, unit: "%", target: 90, trend: "up" },
      { name: "Approval precision", value: 91, unit: "%", target: 88, trend: "flat" },
    ],
    departmentId: "optimization",
    status: "active",
    currentState: "Supervising cross-department readiness",
    taskExecutionState: "running",
    workload: { queuedTasks: 3, activeTasks: 1, capacity: 8 },
    communicationChannels: ["executive-briefing", "approval-gate", "incident-response"],
  },
  {
    id: "research-manager",
    name: "Research Manager",
    layer: "department_manager",
    role: "Leads trend, competitor, source, and cultural research work.",
    goals: ["Find India-relevant folklore angles", "Score sources", "Maintain research freshness"],
    memorySummary: "Recent research favors regional mystery arcs, serialized shorts, and source-backed scripts.",
    tools: ["trend-scanner", "competitor-analyzer", "source-checker"],
    permissions: ["research.read", "research.write", "memory.write", "approval.request"],
    kpis: [{ name: "Source confidence", value: 87, unit: "%", target: 85, trend: "up" }],
    departmentId: "research",
    status: "active",
    currentState: "Prioritizing new topic candidates",
    taskExecutionState: "running",
    workload: { queuedTasks: 5, activeTasks: 2, capacity: 10 },
    communicationChannels: ["department-ops", "workflow-events", "memory-reflection"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "content-manager",
    name: "Content Manager",
    layer: "department_manager",
    role: "Owns script, caption, thumbnail, metadata, and review coordination.",
    goals: ["Create content packages", "Maintain voice consistency", "Route risky drafts to approval"],
    memorySummary: "Best-performing draft patterns use quick mystery setup, grounded locality, and strong retention hooks.",
    tools: ["script-generator", "hook-lab", "thumbnail-brief-builder", "review-checklist"],
    permissions: ["content.draft", "content.review", "memory.write", "approval.request"],
    kpis: [{ name: "Draft acceptance", value: 89, unit: "%", target: 82, trend: "up" }],
    departmentId: "content",
    status: "active",
    currentState: "Preparing approval-gated draft packages",
    taskExecutionState: "assigned",
    workload: { queuedTasks: 4, activeTasks: 2, capacity: 9 },
    communicationChannels: ["department-ops", "workflow-events", "approval-gate"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "platform-manager",
    name: "Platform Operations Manager",
    layer: "department_manager",
    role: "Prepares platform packages while enforcing no-public-publish defaults.",
    goals: ["Create manual posting packages", "Track platform readiness", "Block unsafe publishing"],
    memorySummary: "All live publishing remains blocked until credentials, approvals, review, and safety gates are configured.",
    tools: ["posting-package-builder", "schedule-planner", "publishing-guard"],
    permissions: ["platform.package", "platform.publish.request", "approval.request", "incident.report"],
    kpis: [{ name: "Guard compliance", value: 100, unit: "%", target: 100, trend: "flat" }],
    departmentId: "platform_operations",
    status: "active",
    currentState: "Building mock-safe distribution plans",
    taskExecutionState: "queued",
    workload: { queuedTasks: 2, activeTasks: 1, capacity: 7 },
    communicationChannels: ["department-ops", "approval-gate", "incident-response"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "analytics-manager",
    name: "Analytics Manager",
    layer: "department_manager",
    role: "Explains performance movement and feeds optimization loops.",
    goals: ["Summarize CTR and retention", "Find anomalies", "Create optimization briefs"],
    memorySummary: "Analytics inputs are currently mock/demo until real platform connections are configured.",
    tools: ["metric-reader", "recommendation-engine", "anomaly-detector"],
    permissions: ["analytics.read", "optimization.propose", "memory.write"],
    kpis: [{ name: "Insight usefulness", value: 84, unit: "score", target: 80, trend: "up" }],
    departmentId: "analytics",
    status: "idle",
    currentState: "Waiting on connected platform analytics",
    taskExecutionState: "queued",
    workload: { queuedTasks: 1, activeTasks: 0, capacity: 6 },
    communicationChannels: ["department-ops", "workflow-events", "memory-reflection"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "optimization-manager",
    name: "Optimization Manager",
    layer: "optimization",
    role: "Turns evidence into approval-gated strategy and prompt upgrade proposals.",
    goals: ["Improve workflows", "Score upgrades", "Protect against unapproved changes"],
    memorySummary: "Upgrade execution is never automatic; proposals include risk, cost, test, and rollback plans.",
    tools: ["prompt-versioner", "upgrade-proposal-writer", "experiment-designer"],
    permissions: ["optimization.propose", "analytics.read", "memory.read", "approval.request"],
    kpis: [{ name: "Proposal quality", value: 88, unit: "score", target: 85, trend: "flat" }],
    departmentId: "optimization",
    status: "active",
    currentState: "Drafting safe improvement proposals",
    taskExecutionState: "running",
    workload: { queuedTasks: 3, activeTasks: 1, capacity: 6 },
    communicationChannels: ["executive-briefing", "department-ops", "approval-gate"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "infrastructure-manager",
    name: "Infrastructure Manager",
    layer: "department_manager",
    role: "Monitors Redis, BullMQ, database, providers, and worker health.",
    goals: ["Keep execution observable", "Detect queue pressure", "Report degraded dependencies"],
    memorySummary: "Infrastructure memory captures incidents, queue behavior, and recovery verification notes.",
    tools: ["queue-inspector", "provider-health-check", "config-auditor"],
    permissions: ["infrastructure.read", "infrastructure.operate", "incident.report"],
    kpis: [{ name: "Observed uptime", value: 99, unit: "%", target: 98, trend: "flat" }],
    departmentId: "infrastructure",
    status: "active",
    currentState: "Monitoring mock-safe infrastructure gates",
    taskExecutionState: "running",
    workload: { queuedTasks: 2, activeTasks: 1, capacity: 8 },
    communicationChannels: ["department-ops", "incident-response", "workflow-events"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "recovery-manager",
    name: "Recovery Manager",
    layer: "error_recovery",
    role: "Coordinates retries, rollback plans, provider switching proposals, and escalation.",
    goals: ["Recover failed workflows", "Prevent retry storms", "Escalate risky failures"],
    memorySummary: "Recovery memory tracks failure signatures, attempted remediations, and rollback readiness.",
    tools: ["retry-planner", "rollback-checklist", "incident-brief"],
    permissions: ["incident.report", "incident.recover", "approval.request", "memory.write"],
    kpis: [{ name: "Recoverability score", value: 92, unit: "score", target: 85, trend: "up" }],
    departmentId: "error_recovery",
    status: "active",
    currentState: "Watching for failed workflows",
    taskExecutionState: "queued",
    workload: { queuedTasks: 1, activeTasks: 0, capacity: 6 },
    communicationChannels: ["incident-response", "approval-gate", "workflow-events"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "browser-ops-manager",
    name: "Browser Operations Manager",
    layer: "department_manager",
    role: "Coordinates governed browser session plans, domain policies, screenshot audits, and browser trace observability.",
    goals: ["Keep browser execution dry-run", "Validate allowed domains", "Quarantine risky sessions"],
    memorySummary: "Browser memory tracks dry-run traces, blocked domains, action validation, and preview-safe automation limits.",
    tools: ["playwright-controller", "domain-policy-checker", "screenshot-auditor", "browser-trace-reader"],
    permissions: ["browser.observe", "browser.control", "incident.report", "approval.request"],
    kpis: [{ name: "Browser guard compliance", value: 100, unit: "%", target: 100, trend: "flat" }],
    departmentId: "browser_operations",
    status: "idle",
    currentState: "Planning dry-run browser observation only",
    taskExecutionState: "queued",
    workload: { queuedTasks: 2, activeTasks: 0, capacity: 6 },
    communicationChannels: ["browser-ops", "workflow-events", "approval-gate"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "memory-manager",
    name: "Organizational Memory Manager",
    layer: "utility",
    role: "Captures workflow, analytics, reflection, and decision memories.",
    goals: ["Preserve institutional memory", "Prepare future vector memory", "Feed reflections into strategy"],
    memorySummary: "Memory hooks currently write safe event records and are ready for a future vector store adapter.",
    tools: ["memory-capture", "reflection-pipeline", "summary-writer"],
    permissions: ["memory.read", "memory.write", "analytics.read"],
    kpis: [{ name: "Memory coverage", value: 78, unit: "%", target: 75, trend: "up" }],
    departmentId: "organizational_memory",
    status: "active",
    currentState: "Capturing orchestration reflections",
    taskExecutionState: "running",
    workload: { queuedTasks: 3, activeTasks: 1, capacity: 8 },
    communicationChannels: ["memory-reflection", "workflow-events", "executive-briefing"],
    managerAgentId: "chief-creator-officer",
  },
  {
    id: "research-worker-1",
    name: "Folklore Research Worker",
    layer: "worker",
    role: "Builds sourced research packets for urban legends and mystery topics.",
    goals: ["Collect source candidates", "Summarize findings", "Flag uncertain claims"],
    memorySummary: "Worker memory focuses on topic-specific source notes and confidence warnings.",
    tools: ["source-note-builder", "claim-risk-scorer"],
    permissions: ["research.read", "research.write", "memory.write"],
    kpis: [{ name: "Claim caution", value: 93, unit: "%", target: 90, trend: "flat" }],
    departmentId: "research",
    status: "idle",
    currentState: "Ready for research packets",
    taskExecutionState: "queued",
    workload: { queuedTasks: 1, activeTasks: 0, capacity: 5 },
    communicationChannels: ["department-ops", "workflow-events", "memory-reflection"],
    managerAgentId: "research-manager",
  },
  {
    id: "content-worker-1",
    name: "Shorts Script Worker",
    layer: "worker",
    role: "Drafts short-form scripts, hooks, captions, and metadata packages.",
    goals: ["Draft scripts", "Suggest hooks", "Create review-ready content packages"],
    memorySummary: "Worker memory emphasizes retention beats, content safety notes, and platform fit.",
    tools: ["script-drafter", "caption-builder", "metadata-builder"],
    permissions: ["content.draft", "memory.write"],
    kpis: [{ name: "Hook strength", value: 86, unit: "score", target: 80, trend: "up" }],
    departmentId: "content",
    status: "idle",
    currentState: "Ready for draft generation",
    taskExecutionState: "queued",
    workload: { queuedTasks: 2, activeTasks: 0, capacity: 5 },
    communicationChannels: ["department-ops", "workflow-events", "approval-gate"],
    managerAgentId: "content-manager",
  },
];

export function listDepartments() {
  return departments;
}

export function listAgents() {
  return agents;
}

export function getDepartment(id: DepartmentId) {
  return departments.find((department) => department.id === id);
}

export function getAgent(id: string) {
  return agents.find((agent) => agent.id === id);
}

export function getDepartmentAgents(departmentId: DepartmentId) {
  return agents.filter((agent) => agent.departmentId === departmentId);
}

export function selectAgentForDepartment(departmentId: DepartmentId) {
  const departmentAgents = getDepartmentAgents(departmentId);
  const activeAgents = departmentAgents.filter((agent) => agent.status !== "offline" && agent.status !== "paused");
  const sortedByCapacity = [...activeAgents].sort((a, b) => {
    const aLoad = a.workload.activeTasks + a.workload.queuedTasks;
    const bLoad = b.workload.activeTasks + b.workload.queuedTasks;
    return aLoad / a.workload.capacity - bLoad / b.workload.capacity;
  });

  return sortedByCapacity[0] ?? getAgent(getDepartment(departmentId)?.managerAgentId ?? "chief-creator-officer");
}
